#include "inference_engine.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "model_data.h" // Generated by xxd -i

// TFLM Globals
namespace {
    const tflite::Model* model = nullptr;
    tflite::MicroInterpreter* interpreter = nullptr;
    TfLiteTensor* input = nullptr;
    TfLiteTensor* output = nullptr;

    // Arena size: 80KB constraint
    const int kTensorArenaSize = 80 * 1024;
    uint8_t tensor_arena[kTensorArenaSize];
}

InferenceEngine::InferenceEngine() {}

bool InferenceEngine::begin() {
    model = tflite::GetModel(model_quantized_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        return false;
    }

    // Use AllOpsResolver to automatically handle Conv1D to Conv2D/Reshape mappings
    static tflite::AllOpsResolver resolver;

    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, kTensorArenaSize);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        return false;
    }

    input = interpreter->input(0);
    output = interpreter->output(0);
    _initialized = true;
    return true;
}

bool InferenceEngine::run_anomaly_detection(float window[12][6]) {
    if (!_initialized) {
        // Fallback: Rule-based logic
        if (window[11][0] > 40.5f || window[11][1] > 130.0f) return true;
        return false;
    }

    // 1. Prepare Input (Normalization)
    for (int i = 0; i < 12; i++) {
        input->data.f[i * 6 + 0] = normalize_temp(window[i][0]);
        input->data.f[i * 6 + 1] = normalize_bpm(window[i][1]);
        input->data.f[i * 6 + 2] = normalize_spo2(window[i][2]);
        input->data.f[i * 6 + 3] = normalize_accel(window[i][3]);
        input->data.f[i * 6 + 4] = normalize_accel(window[i][4]);
        input->data.f[i * 6 + 5] = normalize_accel(window[i][5]);
    }

    // 2. Run Inference
    if (interpreter->Invoke() != kTfLiteOk) {
        // Fallback on failure
        return (window[11][0] > 40.5f || window[11][1] > 130.0f);
    }

    // 3. Calculate Reconstruction MSE
    float total_mse = 0;
    for (int i = 0; i < 12 * 6; i++) {
        float diff = input->data.f[i] - output->data.f[i];
        total_mse += diff * diff;
    }
    _last_mse = total_mse / (12.0f * 6.0f);

    // 4. Threshold Check
    return _last_mse > _threshold;
}
